spring.application.name=smart-lead-generator
ai.huggingface.token=${HF_TOKEN}

spring.datasource.url=jdbc:postgresql://localhost:5432/smartlead
spring.datasource.username=smartlead
spring.datasource.password=smartlead
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.flyway.enabled=true

logging.level.org.flywaydb=DEBUG

app.sqs.lead-qualification-queue=smartlead-lead-qualification
spring.cloud.aws.region.static=us-east-1
spring.profiles.active=kafka

# Kafka
app.kafka.lead-qualification-topic=smartlead-lead-qualification
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

spring.kafka.consumer.group-id=smart-lead-generator
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=com.hamza.smartleadgenerator.qualification
spring.kafka.consumer.properties.spring.json.value.default.type=com.hamza.smartleadgenerator.qualification.LeadQualificationJob

