spring.application.name=smart-lead-generator
ai.huggingface.token=${HF_TOKEN}

spring.datasource.url=jdbc:postgresql://localhost:5432/smartlead
spring.datasource.username=smartlead
spring.datasource.password=smartlead
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.flyway.enabled=true

logging.level.org.flywaydb=DEBUG